services:
  db:
    image: postgres:15-alpine
    container_name: tmsc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tmsc
      POSTGRES_PASSWORD: tmsc_password
      POSTGRES_DB: tmsc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
